#############################################################################
# Makefile for building: vokoscreen
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Dec 26 00:04:27 2012
# Project:  vokoscreen.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile vokoscreen.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I/usr/include/QtTest -IQtSingleApplication -Ilibqxt -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lX11 -lQtTest -L/usr/lib64 -lQtGui -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		screencast.cpp \
		regionselection.cpp \
		QvkLupe.cpp \
		QvkWebcam.cpp \
		QvkWinInfo.cpp \
		QtSingleApplication/qtsingleapplication.cpp \
		QtSingleApplication/qtlocalpeer.cpp \
		libqxt/qxtglobal.cpp \
		libqxt/qxtwindowsystem_x11.cpp \
		libqxt/qxtglobalshortcut_x11.cpp \
		libqxt/qxtglobalshortcut.cpp moc_screencast.cpp \
		moc_regionselection.cpp \
		moc_QvkLupe.cpp \
		moc_QvkWebcam.cpp \
		moc_QvkWinInfo.cpp \
		moc_qtsingleapplication.cpp \
		moc_qtlocalpeer.cpp \
		moc_qxtglobalshortcut.cpp \
		qrc_screencast.cpp
OBJECTS       = main.o \
		screencast.o \
		regionselection.o \
		QvkLupe.o \
		QvkWebcam.o \
		QvkWinInfo.o \
		qtsingleapplication.o \
		qtlocalpeer.o \
		qxtglobal.o \
		qxtwindowsystem_x11.o \
		qxtglobalshortcut_x11.o \
		qxtglobalshortcut.o \
		moc_screencast.o \
		moc_regionselection.o \
		moc_QvkLupe.o \
		moc_QvkWebcam.o \
		moc_QvkWinInfo.o \
		moc_qtsingleapplication.o \
		moc_qtlocalpeer.o \
		moc_qxtglobalshortcut.o \
		qrc_screencast.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		QtSingleApplication/qtsingleapplication.pri \
		libqxt/libqxt.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		vokoscreen.pro
QMAKE_TARGET  = vokoscreen
DESTDIR       = 
TARGET        = vokoscreen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): compiler_TSQM_make_all $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vokoscreen.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		QtSingleApplication/qtsingleapplication.pri \
		libqxt/libqxt.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtTest.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -o Makefile vokoscreen.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
QtSingleApplication/qtsingleapplication.pri:
libqxt/libqxt.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qtestlib.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtTest.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile vokoscreen.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vokoscreen1.0.0 || $(MKDIR) .tmp/vokoscreen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vokoscreen1.0.0/ && $(COPY_FILE) --parents language/vokoscreen_de_AT.ts language/vokoscreen_de_CH.ts language/vokoscreen_de_DE.ts language/vokoscreen_es_ES.ts language/vokoscreen_fr_FR.ts language/vokoscreen_it_IT.ts language/vokoscreen_nl_NL.ts language/vokoscreen_pl_PL.ts language/vokoscreen_sv_SE.ts .tmp/vokoscreen1.0.0/ && $(COPY_FILE) --parents screencast.h regionselection.h QvkLupe.h QvkWebcam.h QvkWinInfo.h QtSingleApplication/qtsingleapplication.h QtSingleApplication/qtlocalpeer.h libqxt/qxtglobal.h libqxt/qxtwindowsystem.h libqxt/qxtglobalshortcut.h libqxt/qxtglobalshortcut_p.h .tmp/vokoscreen1.0.0/ && $(COPY_FILE) --parents screencast.qrc .tmp/vokoscreen1.0.0/ && $(COPY_FILE) --parents main.cpp screencast.cpp regionselection.cpp QvkLupe.cpp QvkWebcam.cpp QvkWinInfo.cpp QtSingleApplication/qtsingleapplication.cpp QtSingleApplication/qtlocalpeer.cpp libqxt/qxtglobal.cpp libqxt/qxtwindowsystem_x11.cpp libqxt/qxtglobalshortcut_x11.cpp libqxt/qxtglobalshortcut.cpp .tmp/vokoscreen1.0.0/ && $(COPY_FILE) --parents language/vokoscreen_de_AT.ts language/vokoscreen_de_CH.ts language/vokoscreen_de_DE.ts language/vokoscreen_es_ES.ts language/vokoscreen_fr_FR.ts language/vokoscreen_it_IT.ts language/vokoscreen_nl_NL.ts language/vokoscreen_pl_PL.ts language/vokoscreen_sv_SE.ts .tmp/vokoscreen1.0.0/ && (cd `dirname .tmp/vokoscreen1.0.0` && $(TAR) vokoscreen1.0.0.tar vokoscreen1.0.0 && $(COMPRESS) vokoscreen1.0.0.tar) && $(MOVE) `dirname .tmp/vokoscreen1.0.0`/vokoscreen1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vokoscreen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) vokoscreen
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_TSQM_make_all: language/vokoscreen_de_AT.qm language/vokoscreen_de_CH.qm language/vokoscreen_de_DE.qm language/vokoscreen_es_ES.qm language/vokoscreen_fr_FR.qm language/vokoscreen_it_IT.qm language/vokoscreen_nl_NL.qm language/vokoscreen_pl_PL.qm language/vokoscreen_sv_SE.qm
compiler_TSQM_clean:
	-$(DEL_FILE) language/vokoscreen_de_AT.qm language/vokoscreen_de_CH.qm language/vokoscreen_de_DE.qm language/vokoscreen_es_ES.qm language/vokoscreen_fr_FR.qm language/vokoscreen_it_IT.qm language/vokoscreen_nl_NL.qm language/vokoscreen_pl_PL.qm language/vokoscreen_sv_SE.qm
language/vokoscreen_de_AT.qm: language/vokoscreen_de_AT.ts
	/usr/bin/lrelease language/vokoscreen_de_AT.ts

language/vokoscreen_de_CH.qm: language/vokoscreen_de_CH.ts
	/usr/bin/lrelease language/vokoscreen_de_CH.ts

language/vokoscreen_de_DE.qm: language/vokoscreen_de_DE.ts
	/usr/bin/lrelease language/vokoscreen_de_DE.ts

language/vokoscreen_es_ES.qm: language/vokoscreen_es_ES.ts
	/usr/bin/lrelease language/vokoscreen_es_ES.ts

language/vokoscreen_fr_FR.qm: language/vokoscreen_fr_FR.ts
	/usr/bin/lrelease language/vokoscreen_fr_FR.ts

language/vokoscreen_it_IT.qm: language/vokoscreen_it_IT.ts
	/usr/bin/lrelease language/vokoscreen_it_IT.ts

language/vokoscreen_nl_NL.qm: language/vokoscreen_nl_NL.ts
	/usr/bin/lrelease language/vokoscreen_nl_NL.ts

language/vokoscreen_pl_PL.qm: language/vokoscreen_pl_PL.ts
	/usr/bin/lrelease language/vokoscreen_pl_PL.ts

language/vokoscreen_sv_SE.qm: language/vokoscreen_sv_SE.ts
	/usr/bin/lrelease language/vokoscreen_sv_SE.ts

compiler_moc_header_make_all: moc_screencast.cpp moc_regionselection.cpp moc_QvkLupe.cpp moc_QvkWebcam.cpp moc_QvkWinInfo.cpp moc_qtsingleapplication.cpp moc_qtlocalpeer.cpp moc_qxtglobalshortcut.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_screencast.cpp moc_regionselection.cpp moc_QvkLupe.cpp moc_QvkWebcam.cpp moc_QvkWinInfo.cpp moc_qtsingleapplication.cpp moc_qtlocalpeer.cpp moc_qxtglobalshortcut.cpp
moc_screencast.cpp: regionselection.h \
		QvkLupe.h \
		QvkWebcam.h \
		libqxt/QxtGlobalShortcut \
		libqxt/qxtglobalshortcut.h \
		libqxt/qxtglobal.h \
		QvkWinInfo.h \
		libqxt/qxtwindowsystem.h \
		screencast.h
	/usr/bin/moc $(DEFINES) $(INCPATH) screencast.h -o moc_screencast.cpp

moc_regionselection.cpp: regionselection.h
	/usr/bin/moc $(DEFINES) $(INCPATH) regionselection.h -o moc_regionselection.cpp

moc_QvkLupe.cpp: QvkLupe.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QvkLupe.h -o moc_QvkLupe.cpp

moc_QvkWebcam.cpp: QvkWebcam.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QvkWebcam.h -o moc_QvkWebcam.cpp

moc_QvkWinInfo.cpp: libqxt/qxtwindowsystem.h \
		libqxt/qxtglobal.h \
		QvkWinInfo.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QvkWinInfo.h -o moc_QvkWinInfo.cpp

moc_qtsingleapplication.cpp: QtSingleApplication/qtsingleapplication.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtSingleApplication/qtsingleapplication.h -o moc_qtsingleapplication.cpp

moc_qtlocalpeer.cpp: QtSingleApplication/qtlockedfile.h \
		QtSingleApplication/qtlocalpeer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtSingleApplication/qtlocalpeer.h -o moc_qtlocalpeer.cpp

moc_qxtglobalshortcut.cpp: libqxt/qxtglobal.h \
		libqxt/qxtglobalshortcut.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libqxt/qxtglobalshortcut.h -o moc_qxtglobalshortcut.cpp

compiler_rcc_make_all: qrc_screencast.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_screencast.cpp
qrc_screencast.cpp: screencast.qrc \
		pictures/about.png \
		pictures/red.png \
		pictures/green.png \
		pictures/monitor.png \
		pictures/micro.png \
		pictures/blue.png \
		pictures/videooptionen.png \
		pictures/VokoCola.png \
		pictures/tools.png \
		pictures/vokoscreen.png \
		pictures/yellow.png \
		language/vokoscreen_it_IT.qm \
		language/vokoscreen_sv_SE.qm \
		language/vokoscreen_fr_FR.qm \
		language/vokoscreen_es_ES.qm \
		language/vokoscreen_de_CH.qm \
		language/vokoscreen_pl_PL.qm \
		language/vokoscreen_de_AT.qm \
		language/vokoscreen_de_DE.qm \
		language/vokoscreen_nl_NL.qm
	/usr/bin/rcc -name screencast screencast.qrc -o qrc_screencast.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_TSQM_clean compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp screencast.h \
		regionselection.h \
		QvkLupe.h \
		QvkWebcam.h \
		libqxt/QxtGlobalShortcut \
		libqxt/qxtglobalshortcut.h \
		libqxt/qxtglobal.h \
		QvkWinInfo.h \
		libqxt/qxtwindowsystem.h \
		QtSingleApplication/qtsingleapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

screencast.o: screencast.cpp screencast.h \
		regionselection.h \
		QvkLupe.h \
		QvkWebcam.h \
		libqxt/QxtGlobalShortcut \
		libqxt/qxtglobalshortcut.h \
		libqxt/qxtglobal.h \
		QvkWinInfo.h \
		libqxt/qxtwindowsystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screencast.o screencast.cpp

regionselection.o: regionselection.cpp regionselection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regionselection.o regionselection.cpp

QvkLupe.o: QvkLupe.cpp QvkLupe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QvkLupe.o QvkLupe.cpp

QvkWebcam.o: QvkWebcam.cpp QvkWebcam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QvkWebcam.o QvkWebcam.cpp

QvkWinInfo.o: QvkWinInfo.cpp QvkWinInfo.h \
		libqxt/qxtwindowsystem.h \
		libqxt/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QvkWinInfo.o QvkWinInfo.cpp

qtsingleapplication.o: QtSingleApplication/qtsingleapplication.cpp QtSingleApplication/qtsingleapplication.h \
		QtSingleApplication/qtlocalpeer.h \
		QtSingleApplication/qtlockedfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsingleapplication.o QtSingleApplication/qtsingleapplication.cpp

qtlocalpeer.o: QtSingleApplication/qtlocalpeer.cpp QtSingleApplication/qtlocalpeer.h \
		QtSingleApplication/qtlockedfile.h \
		QtSingleApplication/qtlockedfile.cpp \
		QtSingleApplication/qtlockedfile_win.cpp \
		QtSingleApplication/qtlockedfile_unix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlocalpeer.o QtSingleApplication/qtlocalpeer.cpp

qxtglobal.o: libqxt/qxtglobal.cpp libqxt/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qxtglobal.o libqxt/qxtglobal.cpp

qxtwindowsystem_x11.o: libqxt/qxtwindowsystem_x11.cpp libqxt/qxtwindowsystem.h \
		libqxt/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qxtwindowsystem_x11.o libqxt/qxtwindowsystem_x11.cpp

qxtglobalshortcut_x11.o: libqxt/qxtglobalshortcut_x11.cpp libqxt/qxtglobalshortcut_p.h \
		libqxt/qxtglobalshortcut.h \
		libqxt/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qxtglobalshortcut_x11.o libqxt/qxtglobalshortcut_x11.cpp

qxtglobalshortcut.o: libqxt/qxtglobalshortcut.cpp libqxt/qxtglobalshortcut.h \
		libqxt/qxtglobal.h \
		libqxt/qxtglobalshortcut_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qxtglobalshortcut.o libqxt/qxtglobalshortcut.cpp

moc_screencast.o: moc_screencast.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screencast.o moc_screencast.cpp

moc_regionselection.o: moc_regionselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_regionselection.o moc_regionselection.cpp

moc_QvkLupe.o: moc_QvkLupe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QvkLupe.o moc_QvkLupe.cpp

moc_QvkWebcam.o: moc_QvkWebcam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QvkWebcam.o moc_QvkWebcam.cpp

moc_QvkWinInfo.o: moc_QvkWinInfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QvkWinInfo.o moc_QvkWinInfo.cpp

moc_qtsingleapplication.o: moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtsingleapplication.o moc_qtsingleapplication.cpp

moc_qtlocalpeer.o: moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlocalpeer.o moc_qtlocalpeer.cpp

moc_qxtglobalshortcut.o: moc_qxtglobalshortcut.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qxtglobalshortcut.o moc_qxtglobalshortcut.cpp

qrc_screencast.o: qrc_screencast.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_screencast.o qrc_screencast.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_image: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_FILE) /home/vk/mnt-nfs/Daten/Volker/Programmieren/qt/vokoscreen/vokoscreen/applications/vokoscreen.png $(INSTALL_ROOT)/usr/share/pixmaps/


uninstall_image:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/vokoscreen.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_PROGRAM) /home/vk/mnt-nfs/Daten/Volker/Programmieren/qt/vokoscreen/vokoscreen/applications/vokoscreen.desktop $(INSTALL_ROOT)/usr/share/applications/
	-strip $(INSTALL_ROOT)/usr/share/applications/vokoscreen.desktop


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/vokoscreen.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_man: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/ 
	-$(INSTALL_DIR) /home/vk/mnt-nfs/Daten/Volker/Programmieren/qt/vokoscreen/vokoscreen/man $(INSTALL_ROOT)/usr/share/


uninstall_man:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/man
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ 


install:  install_target install_image install_desktop install_man  FORCE

uninstall: uninstall_target uninstall_image uninstall_desktop uninstall_man   FORCE

FORCE:

