/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i vokoscreen_adaptor.h -a :vokoscreen_adaptor.cpp vokoscreen.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "vokoscreen_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VokoscreenInterfaceAdaptor
 */

VokoscreenInterfaceAdaptor::VokoscreenInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VokoscreenInterfaceAdaptor::~VokoscreenInterfaceAdaptor()
{
    // destructor
}

void VokoscreenInterfaceAdaptor::Stop()
{
    // handle method call org.vokoscreen.screencast.vokoscreenInterface.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

void VokoscreenInterfaceAdaptor::preRecord()
{
    // handle method call org.vokoscreen.screencast.vokoscreenInterface.preRecord
    QMetaObject::invokeMethod(parent(), "preRecord");
}

void VokoscreenInterfaceAdaptor::setAudioOff()
{
    // handle method call org.vokoscreen.screencast.vokoscreenInterface.setAudioOff
    QMetaObject::invokeMethod(parent(), "setAudioOff");
}

