/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a vokoscreen_adaptor.h: vokoscreen.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VOKOSCREEN_ADAPTOR_H
#define VOKOSCREEN_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.vokoscreen.screencast.vokoscreenInterface
 */
class VokoscreenInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.vokoscreen.screencast.vokoscreenInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.vokoscreen.screencast.vokoscreenInterface\">\n"
"    <method name=\"preRecord\"/>\n"
"    <method name=\"Stop\"/>\n"
"    <method name=\"setAudioOff\"/>\n"
"  </interface>\n"
        "")
public:
    VokoscreenInterfaceAdaptor(QObject *parent);
    virtual ~VokoscreenInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Stop();
    void preRecord();
    void setAudioOff();
Q_SIGNALS: // SIGNALS
};

#endif
