######################################################################
# Automatically generated by qmake (2.01a) So. Sep 2 17:10:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qxtglobal.h qxtwindowsystem.h qxtglobalshortcut.h qxtglobalshortcut_p.h 
SOURCES += qxtglobal.cpp qxtwindowsystem_x11.cpp qxtglobalshortcut_x11.cpp QxtGlobalShortcut.cpp

LIBS += -lX11
